Library/Books/urls.py
from django.contrib import admin
from django.urls import path
from Books import views
app_name='Books'
urlpatterns = [
    path('',views.home,name="home"),
    path('add',views.add_books,name="add"),
    path('view',views.view_books,name="view"),
    path('search', views.search, name="search"),
    path('detail/<int:p>',views.detail,name="detail"),
    path('edit/<int:e>',views.edit,name="edit"),
    path('delete/<int:i>',views.delete,name="delete"),
    path('search',views.search,name="search"),
]

Library/Library/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Books.urls')),
    path('Users/',include('Users.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Library/Users/urls.py
"""
URL configuration for Library project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

from django.contrib import admin
from django.urls import path
from Users import views
app_name='Users'

urlpatterns = [

    path('reg',views.register,name="register"),
    path('login',views.user_login,name="login"),
    path('logout',views.user_logout,name="logout"),
    path('view',views.view_users,name="view1"),
]

Library/Books/models.py
from django.db import models

# Create your models here.

class Book(models.Model):
    title=models.CharField(max_length=20)
    author=models.CharField(max_length=20)
    pages=models.IntegerField()
    price=models.IntegerField()
    language=models.CharField(max_length=20)
    cover=models.ImageField(upload_to="images")
    pdf=models.FileField(upload_to="pdf")

    def __str__(self):
        return self.title

Library/Users/models.py
from django.db import models

# Create your models here.

# Table Users



class users(models.Model):
    name=models.CharField(max_length=20)
    age=models.IntegerField()
    place=models.CharField(max_length=20)
    gender=models.CharField(max_length=20)
    email=models.CharField(max_length=20)

    def __str__(self):
        return self.name

Library/Books/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.db.models import Q

# Create your views here.

from Books.models import Book
def home(request):
    context={'name':'Arun','age':27}
    return render(request,'home.html',context)

@login_required
def add_books(request):
    if(request.method=="POST"):
        t=request.POST['t']
        a=request.POST['a']
        p=request.POST['p']
        l=request.POST['l']
        pa=request.POST['pa']

        c=request.FILES.get('i')
        f=request.FILES.get('f')

        b=Book.objects.create(title=t,author=a,price=p,language=l,pages=pa,cover=c,pdf=f)   #creates a new record inside table Book
        b.save()   #saves the record inside table
        return view_books(request)
    return render(request,'add.html')

def view_books(request):
    k=Book.objects.all()    #Read all records from table Books and assigns it to k
    return render(request,'view.html',{'Book':k})

def detail(request,p):
    k=Book.objects.get(id=p)
    return render(request,'detail.html',{'book':k})

@login_required
def edit(request,e):
    k = Book.objects.get(id=e)

    if(request.method=="POST"):
        k.title=request.POST['t']
        k.author=request.POST['a']
        k.price=request.POST['p']
        k.language=request.POST['l']
        k.pages=request.POST['pa']

        if(request.FILES.get('i')==None):
            k.save()
        else:
            k.cover=request.FILES.get('i')

        if(request.FILES.get('f') == None):
            k.save()
        else:
            k.cover = request.FILES.get('f')

        k.save()
        return view_books(request)

    return render(request,'edit.html',{'book':k})


@login_required
def delete(request,i):
    k=Book.objects.get(id=i)
    k.delete()
    return view_books(request)

def search(request):
    k=None   #initialise k as None
    if(request.method=="POST"):
        query=request.POST['q']  #get the input key from form
        print(query)
        if query:
            k=Book.objects.filter(Q(title__icontains=query) | Q(author__icontains=query))  #it checks the key in title and author field of every records.  (it uses in the conditions or/and)
            #filter function returns only the matching records
    return render(request,'search.html',{'book':k})

Library/Users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from django.contrib.auth.decorators import login_required
from Users.models import users
from django.http import HttpResponse

def register(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p=request.POST['p']
        cp=request.POST['cp']
        f=request.POST['f']
        l=request.POST['l']
        e=request.POST['e']

        if(p==cp):
            u=User.objects.create_user(username=u,password=p,first_name=f,last_name=l,email=e)
            u.save()

        else:
            return HttpResponse("Passwords are not same")
        return redirect('Users:login')


    return render(request,'register.html')

def user_login(request):
    if(request.method=="POST"):
        u = request.POST['u']
        p = request.POST['p']
        user=authenticate(username=u,password=p)
        if user:
            login(request,user)
            return redirect('Books:home')
        else:
            return HttpResponse("Invalid")

    return render(request,'login.html')

@login_required
def user_logout(request):
    logout(request)
    return redirect('Users:login')

def view_users(request):
    k=user.objects.all()
    context={'Users':k}
    return render(request,'view1.html',{'Users':k})

Library/templates/add.html
<!DOCTYPE html>
{% extends 'base.html'%}
{% load static %}
{% block content%}
<h2>Add Books</h2>
<form method="POST" enctype="multipart/form-data">

{% csrf_token %}
<div class="mb-3 bg-secondary">
  <label class="form-label">Title</label>
  <input type="text" class="form-control" name="t" placeholder="Enter the title">
</div>
    <div class="mb-3">
  <label class="form-label">Author</label>
  <input type="text" class="form-control" name="a" placeholder="Enter the author name">
</div>
    <div class="mb-3">
        <label class="form-label">Price</label>
        <input type="number" class="form-control" name="p" placeholder="Enter the price">
    </div>
    <div class="mb-3">
  <label class="form-label">Language</label>
  <input type="text" class="form-control" name="l" placeholder="Enter the language">
</div>
   <div class="mb-3">
  <label class="form-label">pages</label>
  <input type="number" class="form-control" name="pa" placeholder="Enter the pages">
</div>
    <div class="mb-3">
        <label class="form-label">Cover</label>
        <input type="file" class="form-control" name="i">
    </div>
    <div class="mb-3">
        <label class="form-label">Pdf</label>
        <input type="file" class="form-control" name="f">
    </div>
    <div class="mb-3">
        <input type="submit" value="ADD">
    </div>
</form>
{% endblock %}

Library/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand text-light" href="#">LIBRARY APP</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active text-light" aria-current="page" href="{% url 'Books:home'%}">Home</a>
        </li>
          {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link text-light" href="{% url 'Books:add' %}">Add books</a>
        </li>

         <li class="nav-item">
          <a class="nav-link text-light" href="{% url 'Books:view'%}">View books</a>
        </li>


                    <li class="nav-item">
          <a class="nav-link text-light" href="{% url 'Users:logout'%}">Logout</a>
        </li>
      </ul>

        {% else %}

          <li class="nav-item">
          <a class="nav-link text-light" href="{% url 'Users:register'%}">Register</a>
        </li>

          <li class="nav-item">
          <a class="nav-link text-light" href="{% url 'Users:login'%}">Login</a>
        </li>


        {% endif %}

                <form method="POST" class="d-flex" style="margin-left:200px;" action="{% url 'Books:search'%}">
                    {% csrf_token %}
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>

    </div>
  </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

Library/templates/detail.html
<!DOCTYPE html>
{% extends 'base.html'%}
{% load static %}
{% block content%}
<div class="container">
<h2 class="text-center">Book Details</h2>
<div class="card mb-3" style="max-width: 800px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="{{book.cover.url}}" class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{book.title}}</h5>
        <p class="card-text">{{book.author}}</p>
        <p class="card-text">{{book.language}}</p>
          <p class="card-text">{{book.price}}</p>
          <p class="card-text">{{book.pages}}</p>
          <a href="{{book.pdf.url}}" class="btn btn-danger mt-5">Download</a>
      </div>
    </div>
  </div>
</div>
</div>
{% endblock %}

Library/templates/edit.html
<!DOCTYPE html>
{% extends 'base.html'%}
{% load static %}
{% block content%}
<h2 class="text-center">Edit Book Details</h2>
<form method="POST" enctype="multipart/form-data">

{% csrf_token %}
<div class="mb-3 bg-secondary">
  <label class="form-label">Title</label>
  <input type="text" class="form-control" name="t" value="{{book.title}}" placeholder="Enter the title">
</div>
    <div class="mb-3">
  <label class="form-label">Author</label>
  <input type="text" class="form-control" name="a" value="{{book.author}}" placeholder="Enter the author name">
</div>
    <div class="mb-3">
        <label class="form-label">Price</label>
        <input type="number" class="form-control" name="p" value="{{book.price}}" placeholder="Enter the price">
    </div>
    <div class="mb-3">
  <label class="form-label">Language</label>
  <input type="text" class="form-control" name="l" value="{{book.language}}" placeholder="Enter the language">
</div>
   <div class="mb-3">
  <label class="form-label">pages</label>
  <input type="number" class="form-control" name="pa" value={{book.pages}} placeholder="Enter the pages">
</div>
    <div class="mb-3">
        <label class="form-label">Cover</label>
        <img src="{{book.cover.url}}">
        <input type="file" class="form-control" name="i">
    </div>
    <div class="mb-3">
        <label class="form-label">Pdf</label>
        <a href="{{book.pdf.url}}">pdf</a>
        <input type="file" class="form-control" name="f">
    </div>
    <div class="mb-3">
        <input type="submit" value="ADD">
    </div>
</form>
{% endblock %}

Library/templates/home.html
<!DOCTYPE html>
{% extends 'base.html'%}
{% load static %}
{% block content%}
<div class="text-center">
<h2>Welcome to Library<span><br>
{% if user.is_authenticated %}
<h2>{{user.username}}</h2>
{% else %}
    Guest</span></h2>
{% endif %}
    </div>
{% endblock %}

Library/templates/login.html
<!DOCTYPE html>
{% extends 'base.html'%}
{% load static %}
{% block content%}
<h2>Login</h2>
<form method="POST">

{% csrf_token %}
<div class="mb-3 bg-secondary">
  <label class="form-label">Username</label>
  <input type="text" class="form-control" name="u" placeholder="Enter the username">
</div>

    <div class="mb-3 bg-secondary">
  <label class="form-label">Password</label>
  <input type="password" class="form-control" name="p" placeholder="Enter the password">
</div>

        <div class="mb-3 bg-secondary">
  <input type="Submit" class="form-control">
</div>

</form>
{% endblock %}

Library/templates/register.html
<!DOCTYPE html>
{% extends 'base.html'%}
{% load static %}
{% block content%}
<h2>Register</h2>
<form method="POST">

{% csrf_token %}
<div class="mb-3 bg-secondary">
  <label class="form-label">Username</label>
  <input type="text" class="form-control" name="u" placeholder="Enter the username">
</div>

    <div class="mb-3 bg-secondary">
  <label class="form-label">Password</label>
  <input type="password" class="form-control" name="p" placeholder="Enter the password">
</div>

        <div class="mb-3 bg-secondary">
  <label class="form-label">Confirm Password</label>
  <input type="password" class="form-control" name="cp" placeholder="Enter the confirm password">
</div>

    <div class="mb-3 bg-secondary">
  <label class="form-label">Firstname</label>
  <input type="text" class="form-control" name="f" placeholder="Enter the firstname">
</div>

    <div class="mb-3 bg-secondary">
  <label class="form-label">Lastname</label>
  <input type="text" class="form-control" name="l" placeholder="Enter the Lastname">
</div>

    <div class="mb-3 bg-secondary">
  <label class="form-label">Email</label>
  <input type="text" class="form-control" name="e" placeholder="Enter the email">
</div>

    <div class="mb-3 bg-secondary">
  <input type="Submit" class="form-control">
</div>
</form>
{% endblock %}

Library/templates/search.html
{% extends 'base.html'%}
{% load static %}
{% block content%}
<h2>Search Books</h2>
<table class="table table-bordered bg-secondary">
    <tr>
        <th>COVER</th>
        <th>TITLE</th>
        <th>AUTHOR</th>
        <th>LANGUAGE</th>
        <th>PRICE</th>
        <th>PAGES</th>
        <th>DOCUMENT</th>

    </tr>
    {% for i in book %}
    <tr>
        <td><img src="{{i.cover.url}}" class="img-thumbnail" height="150px" width="200px" ></td>
        <td>{{i.title}}</td>
        <td>{{i.author}}</td>
        <td>{{i.language}}</td>
        <td>{{i.price}}</td>
        <td>{{i.pages}}</td>
        <td><a href="{{i.pdf.url}}">Download</a></td>

    </tr>
    {% endfor %}
</table>
{% endblock %}

Library/templates/view.html
<!DOCTYPE html>
{% extends 'base.html'%}
{% load static %}
{% block content%}
<h2>View Books</h2>
<table class="table table-bordered bg-secondary">
    <tr>
        <th>COVER</th>
        <th>TITLE</th>
        <th>AUTHOR</th>
        <th>LANGUAGE</th>
        <th>PRICE</th>
        <th>PAGES</th>
        <th>DOCUMENT</th>
        <th>VIEW</th>
        <th>EDIT</th>
        <th>DELETE</th>
    </tr>
    {% for i in Book %}
    <tr>
        <td><img src="{{i.cover.url}}" class="img-thumbnail" height="150px" width="200px" ></td>
        <td>{{i.title}}</td>
        <td>{{i.author}}</td>
        <td>{{i.language}}</td>
        <td>{{i.price}}</td>
        <td>{{i.pages}}</td>
        <td><a href="{{i.pdf.url}}">Download</a></td>
        <td><a href="{% url 'Books:detail' i.id%}" class="btn btn-danger">view</a></td>
        <td><a href="{% url 'Books:edit' i.id%}" class="btn btn-danger">edit</a></td>
        <td><a href="{% url 'Books:delete' i.id %}" class="btn btn-danger">delete</a></td>
    </tr>
    {% endfor %}
</table>
<!--    <ol>-->
<!--        {% for i in Book %}-->
<!--        <li>-->
<!--        <ul>-->
<!--        <li>Title:{{i.title}}</li>-->
<!--            <li>Author:{{i.author}}</li>-->
<!--            <li>Title:{{i.language}}</li>-->
<!--            <li>Title:{{i.price}}</li>-->
<!--            <li>Title:{{i.pages}}</li>-->
<!--        </ul>-->
<!--</li>-->
<!--        {% endfor %}-->
<!--    </ol>-->


<!--<h2>View Users</h2>-->
<!--<table class="table table-bordered bg-secondary">-->
<!--    <tr>-->
<!--        <th>Name</th>-->
<!--        <th>Age</th>-->
<!--        <th>Place</th>-->
<!--        <th>Gender</th>-->
<!--        <th>Email</th>-->
<!--    </tr>-->
<!--    {% for i in Users %}-->
<!--    <tr>-->
<!--        <td>{{i.name}}</td>-->
<!--        <td>{{i.age}}</td>-->
<!--        <td>{{i.place}}</td>-->
<!--        <td>{{i.gender}}</td>-->
<!--        <td>{{i.email}}</td>-->
<!--    </tr>-->
<!--    {% endfor %}-->
<!--</table>-->
<!--{% endblock %}-->

Library/templates/view1.html
<!DOCTYPE html>
{% extends 'base.html'%}
{% load static %}
{% block content%}
<h2>View Users</h2>
<table class="table table-bordered bg-secondary">
    <tr>
        <th>Name</th>
        <th>Age</th>
        <th>Place</th>
        <th>Gender</th>
        <th>Email</th>
    </tr>
    {% for i in Users %}
    <tr>
        <td>{{i.name}}</td>
        <td>{{i.age}}</td>
        <td>{{i.place}}</td>
        <td>{{i.gender}}</td>
        <td>{{i.email}}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}